// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StandardResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*StandardResponse_Data
	//	*StandardResponse_Error
	Content       isStandardResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *StandardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StandardResponse) GetContent() isStandardResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StandardResponse) GetData() *DataResponse {
	if x != nil {
		if x, ok := x.Content.(*StandardResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *StandardResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Content.(*StandardResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStandardResponse_Content interface {
	isStandardResponse_Content()
}

type StandardResponse_Data struct {
	Data *DataResponse `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type StandardResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*StandardResponse_Data) isStandardResponse_Content() {}

func (*StandardResponse_Error) isStandardResponse_Content() {}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *anypb.Any             `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta          *MetaData              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataResponse) GetMeta() *MetaData {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *MetaData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MetaData) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *MetaData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RegisterEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Otp           string                 `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEmailRequest) Reset() {
	*x = RegisterEmailRequest{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailRequest) ProtoMessage() {}

func (x *RegisterEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RegisterEmailRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type ForgetPasswordEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Otp           string                 `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordEmailRequest) Reset() {
	*x = ForgetPasswordEmailRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordEmailRequest) ProtoMessage() {}

func (x *ForgetPasswordEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordEmailRequest.ProtoReflect.Descriptor instead.
func (*ForgetPasswordEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ForgetPasswordEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ForgetPasswordEmailRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *PushRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PushRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\x1a\x19google/protobuf/any.proto\"\xb8\x01\n" +
	"\x10StandardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.notification.DataResponseH\x00R\x04data\x123\n" +
	"\x05error\x18\x04 \x01(\v2\x1b.notification.ErrorResponseH\x00R\x05errorB\t\n" +
	"\acontent\"j\n" +
	"\fDataResponse\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.notification.MetaDataR\x04meta\"\xd3\x01\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12B\n" +
	"\adetails\x18\x03 \x03(\v2(.notification.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\bMetaData\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"8\n" +
	"\x14RegisterEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otp\">\n" +
	"\x1aForgetPasswordEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otp\"\xcc\x01\n" +
	"\vPushRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x127\n" +
	"\x04data\x18\x04 \x03(\v2#.notification.PushRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9a\x02\n" +
	"\x13NotificationService\x12W\n" +
	"\x11SendRegisterEmail\x12\".notification.RegisterEmailRequest\x1a\x1e.notification.StandardResponse\x12c\n" +
	"\x17SendForgetPasswordEmail\x12(.notification.ForgetPasswordEmailRequest\x1a\x1e.notification.StandardResponse\x12E\n" +
	"\bSendPush\x12\x19.notification.PushRequest\x1a\x1e.notification.StandardResponseB\x1dZ\x1bride-sharing/internal/protob\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notification_proto_goTypes = []any{
	(*StandardResponse)(nil),           // 0: notification.StandardResponse
	(*DataResponse)(nil),               // 1: notification.DataResponse
	(*ErrorResponse)(nil),              // 2: notification.ErrorResponse
	(*MetaData)(nil),                   // 3: notification.MetaData
	(*RegisterEmailRequest)(nil),       // 4: notification.RegisterEmailRequest
	(*ForgetPasswordEmailRequest)(nil), // 5: notification.ForgetPasswordEmailRequest
	(*PushRequest)(nil),                // 6: notification.PushRequest
	nil,                                // 7: notification.ErrorResponse.DetailsEntry
	nil,                                // 8: notification.PushRequest.DataEntry
	(*anypb.Any)(nil),                  // 9: google.protobuf.Any
}
var file_notification_proto_depIdxs = []int32{
	1, // 0: notification.StandardResponse.data:type_name -> notification.DataResponse
	2, // 1: notification.StandardResponse.error:type_name -> notification.ErrorResponse
	9, // 2: notification.DataResponse.payload:type_name -> google.protobuf.Any
	3, // 3: notification.DataResponse.meta:type_name -> notification.MetaData
	7, // 4: notification.ErrorResponse.details:type_name -> notification.ErrorResponse.DetailsEntry
	8, // 5: notification.PushRequest.data:type_name -> notification.PushRequest.DataEntry
	4, // 6: notification.NotificationService.SendRegisterEmail:input_type -> notification.RegisterEmailRequest
	5, // 7: notification.NotificationService.SendForgetPasswordEmail:input_type -> notification.ForgetPasswordEmailRequest
	6, // 8: notification.NotificationService.SendPush:input_type -> notification.PushRequest
	0, // 9: notification.NotificationService.SendRegisterEmail:output_type -> notification.StandardResponse
	0, // 10: notification.NotificationService.SendForgetPasswordEmail:output_type -> notification.StandardResponse
	0, // 11: notification.NotificationService.SendPush:output_type -> notification.StandardResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_notification_proto_msgTypes[0].OneofWrappers = []any{
		(*StandardResponse_Data)(nil),
		(*StandardResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
